name: Publish Package

on:
  push:
    branches:
      - master
    tags:
      - 'v*'  # Matches tags starting with 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'

      - run: |
          echo "@axelnie:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: npm install

      - name: Automated npm Release
        uses: jsynowiec/automated-releases-for-npm-packages@v1
        with:
          npm-token: ${{ secrets.GITHUB_TOKEN }}
          bump: patch  # Options: patch, minor, major
          registry: 'https://npm.pkg.github.com/'

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
