name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'    

      - name: Login to GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
            
      - name: Debug .npmrc file
        run: cat ~/.npmrc | sed 's/_authToken=.*/_authToken=***HIDDEN***/'    

      - name: Publish package
        run: npm publish --registry=https://npm.pkg.github.com/
      
